### ISSUE TITLE
Homebrew repo is using depricated calls to sha1

### ISSUE THREAD

**Issue by arderyp** [jedda/Counterpart#16]
running brew update && brew upgrade results in:

```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/jedda/homebrew-counterpart/counterpart.rb:6:in `<class:Counterpart>'
Please report this to the jedda/counterpart tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/jedda/homebrew-counterpart/counterpart.rb:6:in `<class:Counterpart>'
Please report this to the jedda/counterpart tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/jedda/homebrew-counterpart/counterpart.rb:6:in `<class:Counterpart>'
Please report this to the jedda/counterpart tap!
```

**Comment by Juravenator** [comment]
running `brew tap jedda/counterpart` now doesn't seem to work anymore

```bash
brew tap jedda/counterpart
==> Tapping jedda/counterpart
Cloning into '/usr/local/Homebrew/Library/Taps/jedda/homebrew-counterpart'...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
Checking connectivity... done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/jedda/homebrew-counterpart/counterpart.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/jedda/homebrew-counterpart/counterpart.rb:6:in `<class:Counterpart>'
Please report this to the jedda/counterpart tap!
Error: Cannot tap jedda/counterpart: invalid syntax in tap!
```

**Comment by arderyp** [comment]
Yup.  I think this project has been abandoned.  I simply moved my counterpart Cellar subdirectory to a different location, then fixed my /use/local/counterpart link to point to the executable in the new location. So, my scripts calling counterpart will continue to work, but homebrew will no longer tracking the project (and no longer fail when running update and upgrade), which is fine, since there does not appear to be any active development.

**Comment by pilot33** [comment]
So how can you manually install this script without homebrew?

**Comment by AlexanderWillner** [comment]
My current way to install counterpart: https://github.com/AlexanderWillner/Counterpart
